spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springCloud
    username: gadi821
    password: Gcc821.ro
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
